### ISSUE TITLE
Taiga: Unable to login with TFConnect and the admin page doesn't load

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tf-images#84] opened 2022-07-03 12:11 UTC
Tested on QA Net weblets `v1.4.3-qa3` 
and Testnet weblets `v1.4.3-rc1`

### Description

After successfully deploying a taiga instance through the weblets both on QAnet and on Testnet, i was not able to login to the instance using TFConnect with the following error 

![image](https://user-images.githubusercontent.com/101194226/177039363-7996bd19-488f-4445-888c-053a28919d33.png)

however on TFConnect i did not get an error and it returned that i logged in successfully 

![image](https://user-images.githubusercontent.com/101194226/177039414-7f750b7b-ea91-4509-9e87-2b6658e63329.png)

and i wasn't able to access the admin panel and it just gives `502 Bad Gateway`

![image](https://user-images.githubusercontent.com/101194226/177039458-7d0c376f-6cf9-44a7-906c-a8712d049141.png)

### Steps to reproduce

- Navigate to https://play.qa.grid.tf/#/taiga
- Deploy a taiga instance.
- Navigate to the deployed instance and try to login with TFConnect.
- Navigate to the admin panel

### Logs/Alerts

The logs from running `zinit log`

- QAnet

   [taiga_logs_qa.txt](https://github.com/threefoldtech/grid_weblets/files/9034725/taiga_logs_qa.txt)

- Testnet

   [taiga_logs_test.txt](https://github.com/threefoldtech/grid_weblets/files/9034726/taiga_logs_test.txt)

**Comment by Omarabdul3ziz** [comment] 2022-08-16 10:00
The logs show that the issue is because the `/api/v1/auth` endpoint is not accessible, which is served by the container `docker_taiga-back_1` .
the container exited because the server failed to connect with the db on the container `docker_taiga-db_1` .

because the db is not ready yet. and the server implementation does not retry to connect again. the container exited.

even in the docker-comose file. the `taiga-back` service depends on `taiga-db`. 
but according to [official docs](https://docs.docker.com/compose/startup-order/#:~:text=However%2C%20for%20startup%20Compose%20does%20not%20wait%20until%20a%20container%20is%20%E2%80%9Cready%E2%80%9D%20(whatever%20that%20means%20for%20your%20particular%20application)%20%2D%20only%20until%20it%E2%80%99s%20running) `depends-on` on docker-compose file only make sure the container is up even if the service in it is not ready yet.

tried different approaches to fix this. and found the best one is to restart the container on failure until the DB is ready.

**Comment by hossnys** [comment] 2022-08-16 11:06
i had the same error when tried to install staging taiga instance from this repo https://github.com/threefoldtech/taiga-contrib-threefold-auth and i added that fix in docker-compose file from that pr mentioned above , and that didn't fix the issue

**Comment by Omarabdul3ziz** [comment] 2022-10-13 14:30
this should be fixed with updates from https://github.com/threefoldtech/tf-images/pull/81.
and the new flist: `https://hub.grid.tf/tf-official-apps/grid3_taiga_docker-latest.flist`

**Closed as completed by Omarabdul3ziz** 2022-10-13 14:30 UTC
Labels: type_bug
